package com.ftn.sbnz.rules.cep;

import com.ftn.sbnz.model.events.PotentialDiscoveryEvent;
import java.util.List;
import java.util.UUID;

rule "Detect Undocumented Hotspot"
    no-loop true
    when
        $trigger: PotentialDiscoveryEvent(
            $mineralId: mineralId,
            $location: location
        )
        $events: List(size >= 5) from accumulate (
            $e: PotentialDiscoveryEvent(
                mineralId == $mineralId,
                location == $location
            ) over window:time(45d),
            collectList($e)
        )
        eval(com.ftn.sbnz.model.utils.CepHelper.hasEnoughUsersForHotspot($events))
    then
        System.out.println("-----------------------------------------------------------------");
        System.out.println("!!! UPOZORENJE ADMINISTRATORU: DETEKTOVAN NOVI HOTSPOT !!!");
        System.out.println("Mineral: " + $trigger.getMineralName());
        System.out.println("Lokacija: " + $trigger.getLocation());
        System.out.println("Broj prijava u poslednjih 45 dana: " + $events.size());
        System.out.println("-----------------------------------------------------------------");

        for(Object event : $events){
            drools.delete(event);
        }
end